#!/bin/bash
do_run=1 # Execute(evaluate) the commands
#do_run=0 # Don't evaluate any commands


#cf env concile_mlw_v0 | tail -n +5 | tail -r | tail -n +22 | tail -r > /tmp/env.out
#VCSVCS=$(cat /tmp/env.out | jq -r '.VCAP_SERVICES' 2>/dev/null | tail -r | tail -n +2 | tail -r)

  cmd='VCAP_SERVICES=$(cf env concile_mlw_v0 | tail -n +5 | tail -r | tail -n +22 | tail -r | jq -r '"'"'.VCAP_SERVICES'"'"' 2>/dev/null | tail -r | tail -n +2 | tail -r | tr -d "[:space:]")'
  #echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  #echo 'export VCAP_SERVICES='$VCAP_SERVICES

  export PORT=8001
  echo "PORT:"$PORT
  python3 server.py

