#!/bin/bash
do_run=1 # Execute(evaluate) the commands
#do_run=0 # Don't evaluate any commands
#
#MY_DIR=$(dirname $(readlink -f $0))
MY_DIR="/Users/i830671/git/conciletime/tools"
. $MY_DIR/common.sh
#echo $?
if [ $? -eq 1 ]; then
  echo ""
  echo "Copy the $MY_DIR/common.sh.template file to $MY_DIR/common.sh and adjust before continuing."
  echo ""
  cmd='cp '$MY_DIR/common.sh.template' '$MY_DIR/common.sh
  echo $cmd
  echo ""
  cmd='vi '$MY_DIR/common.sh
  echo $cmd
  echo ""
  exit
fi
echo ""
echo "Including common.sh from "$MY_DIR
echo ""
echo "host:$host port:$port tenant:$tenant org:$org xsa_user:$xsa_user"
xsorcf=$1
targetspace=$2
version=$3
echo "xsorcf:$xsorcf targetspace:$targetspace version:$version"
echo ""
#exit
tmpfile="/tmp/xscfenv.out"
dowait=""
doexport1=""
doexport2=""
if [ "$#" -eq 3 ]; then
  if [ $xsorcf = "xs" ]; then
    dowait=" --wait-indefinitely"
    doexport1=" --export-json /dev/stdout 2>/dev/null | tail -n +5 > $tmpfile"
    echo "XS cool."
  else
    if [ $xsorcf = "cf" ]; then
      doexport1=" | tail -n +5 | tail -r | tail -n +10 | tail -r > $tmpfile"
      doexport2=" | tail -r | tail -n +1 | tail -r"
      echo "CF cool."
    else
      echo "Not XS or CF, try again."
      exit 1
    fi
  fi

  targetspace_uc=$(echo "$targetspace" | tr a-z A-Z)
  targetspace_lc=$(echo "$targetspace" | tr A-Z a-z)

  version_uc=$(echo "$version" | tr a-z A-Z)
  version_lc=$(echo "$version" | tr A-Z a-z)

  echo Post Deploy to TargetSpace $targetspace_uc in Org: $org with Version: $version_uc Starting...
  echo ""

  cmd=$xsorcf' target -o '$org' -s '$targetspace
  echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  #RESULT=$?


  cmd=$xsorcf' target -o '$org' -s '$targetspace
  echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  #RESULT=$?

  #echo 'HDI SERVICE RESULT:'$RESULT

  echo ""

  cmd=$xsorcf' env concile_utl_'$version_lc' '$doexport1
  echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  echo ""
  
  #lineNum=$(grep -n VCAP_APPLICATION /tmp/xscfenv.out | head -n 1 | cut -d: -f1)
  
  #head -n $[$lineNum - 3] /tmp/xscfenv.out

  #lineNum=$[$lineNum - 3]
    
  #echo "lineNum="$lineNum

  #cat /tmp/xscfenv.out  | jq -r '"'"'.VCAP_SERVICES.xsuaa[0].credentials.xsappname'"'"' 2>/dev/null | head -n 1

  cmd='XSAPPNAME=$(cat /tmp/xscfenv.out  | jq -r '"'"'.VCAP_SERVICES.xsuaa[0].credentials.xsappname'"'"' 2>/dev/null | head -n 1)'
  echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  echo 'export XSAPPNAME='$XSAPPNAME


  # File manipulation
  #cmd='sed -e "s/xs_routing_mode=ports/xs_routing_mode=hostnames/g" -i "" auto_install.cfg'


  fromfile='registry-config-xxx.json'
  tofile='registry-config-'$targetspace_uc'.json'

  cmd='cp '$fromfile' '$tofile
  echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  #RESULT=$?

  cmd='sed -e "s/xxx/'$targetspace_lc'/g" -i "" '$tofile
  echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  #RESULT=$?

  cmd='sed -e "s/XXX/'$targetspace_uc'/g" -i "" '$tofile
  echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  #RESULT=$?

  echo ""

  echo "Don't forget to go back and edit the "$tofile" and replace the ZZZZ with your appid."
  cmd='sed -e "s/ZZZZ/'$XSAPPNAME'/g" -i "" '$tofile
  echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  #RESULT=$?

#cf create-service saas-registry application CONCILE_REG -c registry-config-prod.json
  cmd=$xsorcf' create-service saas-registry application CONCILE_REG -c registry-config-'$targetspace_lc'.json'
  echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  echo ""
 
#cf bind-service concile_utl_v0 CONCILE_REG
  cmd=$xsorcf' bind-service concile_utl_'$version_lc' CONCILE_REG'
  echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  echo ""
 
#cf restage concile_utl_v0
  cmd=$xsorcf' restage concile_utl_'$version_lc
  echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  echo ""
 
  #exit 1

else
    echo "Usage ./2_post_deploy xs[cf] targetspace version"
    exit 1
fi
echo ""
echo Post Deploy to TargetSpace $targetspace Finished
echo ""
echo "You should now be able to subscribe/unsubscribe to ConcileTime-$targetspace_uc from subaccounts other than the ConcileTime provider subaccount."
echo ""

echo "Warning! Any subscribers will be taken to the version of conciletime in the space where the '*' route is mapped."
echo "         Unless there is an explicit subdomain.conciletime.com route mapping to a conciletime in a different space."
echo ""

  cmd=$xsorcf' routes --orglevel'
  echo $cmd
  if [ $do_run -eq 1 ]; then eval $cmd; fi
  echo ""
 
echo ""
